import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { InlineLink } from "@/components/ui/inlineLink";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header className="w-full border-b border-border/40 bg-background/95">
      <div className="container flex h-12 max-w-screen-2xl items-center">
        <div className="font-bold">PicsumEditor</div>
      </div>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className="py-2 px-8">
      <div className="flex items-center h-16 text-sm text-muted-foreground">
        <p>
          Build by{" "}
          <InlineLink href="https://x.com/mateuszsiek91">
            @mateuszsiek
          </InlineLink>{" "}
          using{" "}
          <InlineLink href="https://picsum.photos/">picsum.photos</InlineLink>
        </p>
      </div>
    </footer>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, "h-full flex flex-col")}>
        <Header />
        <div className="flex-1 py-2 px-8">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
